# action.yml
name: 'Pull Request Issue Comment'
description: 'Comment on a pull request'
author: 'nickatnight'
inputs:
  body:  # id of input
    description: 'Body of comment'
    required: true
    default: ''
  allow_duplicates:  # id of input
    description: 'Allow duplicate comments if True'
    required: false
    default: true
  report:
    description: 'report coverage results'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'mic'
  color: 'blue'
