#!/usr/bin/env python3

import json
import os
import requests


API_BASE = "https://api.github.com/repos/"
AUTH_HEADER = f"token {os.getenv('GITHUB_TOKEN')}"
INPUT_BODY = os.getenv("INPUT_BODY")

with open(os.getenv("GITHUB_EVENT_PATH")) as json_file:
    event_json = json.load(json_file)

repo_name = event_json["repository"]["full_name"]
repo_url = f"{API_BASE}{repo_name}/"
headers = {"Authorization": AUTH_HEADER}
pr_number = None

if os.getenv("GITHUB_EVENT_NAME") == "pull_request":
    pr_number = event_json["number"]
else:
    pulls = requests.get(f"{repo_url}pulls", headers=headers).json()
    push_head = event_json["after"]
    for pr in pulls:
        if push_head == pr.get("head").get("sha"):
            pr_number = pr["number"]

if not pr_number:
    raise Exception("No PR found.")


req = requests.post(f"{repo_url}pulls/{pr_number}/comments", data={"body": INPUT_BODY}, headers=headers)
req.raise_for_status()
