#!/usr/bin/env python3

import json
import os
import sys

from github import Github


INPUT_BODY = os.getenv("INPUT_BODY")

g = Github(os.getenv("GITHUB_TOKEN"))
with open(os.getenv("GITHUB_EVENT_PATH")) as json_file:
    event_json = json.load(json_file)

repo_name = event_json["repository"]["full_name"]
org, repo = repo_name.split("/")
o = g.get_organization(org)
r = o.get_repo(repo)
pull_request = None

if os.getenv("GITHUB_EVENT_NAME") == "pull_request":
    pull_request = r.get_pull(event_json["number"])
else:
    push_head = event_json["after"]
    for pr in r.get_pulls():
        if push_head == pr.head.sha:
            pull_request = pr

if not pull_request:
    print("No PR found.")
    sys.exit(0)

pull_request.create_issue_comment(INPUT_BODY)
