#!/usr/bin/env python3

import json
import os
import requests


API_BASE = "https://api.github.com/repos/"

INPUT_BODY = os.getenv("INPUT_BODY")

with open(os.getenv("GITHUB_EVENT_PATH")) as json_file:
    event_json = json.load(json_file)

repo_name = event_json["repository"]["full_name"]
repo_url = f"{API_BASE}{repo_name}/"
pr_number = None

if os.getenv("GITHUB_EVENT_NAME") == "pull_request":
    pr_number = event_json["number"]
else:
    pulls = requests.get(f"{repo_url}pulls").json()
    push_head = event_json["after"]
    for pr in pulls:
        if push_head == pr.get("head").get("sha"):
            pr_number = pr["number"]

if not pr_number:
    raise Exception("No PR found.")


requests.post(f"{repo_url}issues/{pr_number}/comments", data={"body": INPUT_BODY})
